###
### hello
GET http://localhost:8888/hello
Accept: application/json


### gw 1
GET http://localhost:8888/gw
Accept: application/json


### gw-hefrpc
POST http://localhost:8888/gw/hefrpc/cn.hefrankeleyn.hefrpc.demo.api.UserService
Content-Type: application/json

{
  "service": "cn.hefrankeleyn.hefrpc.demo.api.UserService",
  "methodSign": "findById#int",
  "args": [300]
}

### gw-direct
POST http://localhost:8888/gw/direct/cn.hefrankeleyn.hefrpc.demo.api.UserService?backend=http://localhost:8081/hefrpc
Content-Type: application/json

{
  "service": "cn.hefrankeleyn.hefrpc.demo.api.UserService",
  "methodSign": "findById#int",
  "args": [300]
}